[project]
name = "soundscript"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "librosa>=1.0.0",
    "numpy>=2.5.3",
    "openai-whisper>=20250625",
    "scipy>=1.18.1",
    "setuptools<81",
    "sounddevice>=0.5.6",
    "tensorflow>=2.21.0",
    "tensorflow-hub>=0.16.1",
    "uvicorn>=0.52.4",
    "websockets>=15.0",
]
